kafka: localhost:9092
topic: test
interval: 1000
samples: 5
format: csvheadless
correlation:
  label: userId
  amount: 5
data:
  - ip=ipv4
  - mac=macaddress
  - lat=latitude
  - lon=longitude
  - timestamp=timestamp
